# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Memoir of the Lower Leisure Class
tagline:          'My Brief Time on Earth'
description:      'Projects and stories by Nathan McLaughlin'
url:              http://nathanmclaughlin.com
baseurl:          /

author:
  name:           'Nathan McLaughlin'
  url:            https://twitter.com/natcromlech
  email:          nmclaughlin@gmail.com 

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
